name: Continuous builds py3.13

on:
  push:
    branches:
      - master
      - development
      - experimental
      - 'test*'
  pull_request:
    branches:
      - master
      - development
      - experimental
      - 'test*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        python-version: ["3.13.0-beta.2"]
      fail-fast: false

    steps:

    - uses: actions/checkout@v4
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Print refs
      run: |
        echo "github.ref is: ${{ github.ref }}"
        echo "github.base_ref is: ${{ github.base_ref }}"

    - name: Upgrade pip, install deps
      run: |
        python -m pip install --upgrade pip
        pip install numpy<2.0.0 # due to lingering issues with other modules
        pip install .[dev]

    - name: List packages so far
      run: |
        pip list

    - name: Run tests
      run: |
        pynml -h

        ./test-ghactions.sh -neuron
